openapi: 3.0.3
info:
  description: Handle the info about currencies in platform
  title: Currency Api
  version: "1.0"
servers:
- url: /
security:
- basicAuth: []
tags:
- description: Available operations for currencies domain.
  name: currencies
paths:
  /v1/currencies:
    get:
      operationId: getCurrencies
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Currency'
                type: array
          description: successful operation
        "401":
          content: {}
          description: Authentication is required to get the requested response
      summary: Get currencies list
      tags:
      - currencies
      x-accepts: application/json
  /v1/currencies/{currencyCode}:
    get:
      operationId: getCurrencyByCode
      parameters:
      - description: The currency ISO code
        explode: false
        in: path
        name: currencyCode
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
          description: successful operation
        "401":
          description: Authentication is required to get the requested response
        "404":
          description: Currency not found
      summary: Get currency detail
      tags:
      - currencies
      x-accepts: application/json
components:
  schemas:
    Currency:
      example:
        symbol: €
        code: EUR
        decimals: 2
      properties:
        symbol:
          example: €
          type: string
        code:
          description: ISO Code of the currency
          example: EUR
          type: string
        decimals:
          example: 2
          type: integer
      required:
      - code
      - decimals
      - symbol
      type: object
  securitySchemes:
    basicAuth:
      scheme: basic
      type: http

